version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: docker/php/DockerFile
    container_name: dewtech-app
    restart: always
    ports:
      - "9000:9000"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./application:/var/www/application
    environment:
      - COMPOSER_HOME=/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=local
      - APP_KEY=base64:OPmiGw1z2z+RrAorpa0nTNTNMIfzSPJMZBmxUDaeErE=
    depends_on:
      - db

  crontab:
    build:
      context: ./
      dockerfile: docker/crontab/DockerFile
    container_name: dewtech-cronjob
    restart: unless-stopped
    working_dir: /etc/cron.d
    volumes:
      - ./docker/crontab/files:/etc/cron.d
      - ./docker/crontab/scripts:/scritps
  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: dewtech-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./application:/var/www/application
      - ./docker/nginx:/etc/nginx/conf.d
  db:
    build:
      context: ./
      dockerfile: docker/db/DockerFile
    container_name: dewtech-db
    restart: always
    environment:
      - POSTGRES_DB=crontab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
